'use strict';

module.exports = [
    require('./subjects'),
    require('./current-medications'),
    require('./demographics'),
    require('./diet.js'),
    require('./early-history'),
    require('./everyday-cognition'),
    require('./family-tree'),
    require('./initial-m00'),
    require('./initial-m06'),
    require('./initial-m12'),
    require('./initial-m18'),
    require('./initial-m24'),
    require('./medical-history'),
	require('./mood'),
    require('./memtrax'),
    require('./ncpt-gonogo'),
    require('./ncpt-memoryspan'),
    require('./ncpt-overall'),
    require('./ncpt-reversememoryspan'),
    require('./ncpt-trailmakingb'),
	require('./osutbi-impacts'),
	require('./osutbi-injuries'),
	require('./osutbi'),
	require('./quality-of-life'),
	require('./quolibri'),
	require('./rivermead'),
	require('./sleep')
];
