export const GET_CONSENT_DOCS = 'GET_CONSENT_DOCS';
export const GET_CONSENT_DOCS_SUCCESS = 'GET_CONSENT_DOCS_SUCCESS';
export const GET_CONSENT_DOCS_FAILURE = 'GET_CONSENT_DOCS_FAILURE';

export const SIGN_CONSENT = 'SIGN_CONSENT';
export const SIGN_CONSENT_SUCCESS = 'SIGN_CONSENT_SUCCESS';
export const SIGN_CONSENT_FAILURE = 'SIGN_CONSENT_FAILURE';
