export const UPDATE_SURVEY_ANSWERS = 'UPDATE_SURVEY_ANSWERS';
export const GET_SURVEY_BY_ID_SUCCESS = 'GET_SURVEY_BY_ID_SUCCESS';
export const SUBMIT_SURVEY = 'SUBMIT_SURVEY';
export const SUBMIT_SURVEY_FAILURE = 'SUBMIT_SURVEY_FAILURE';
export const SUBMIT_SURVEY_SUCCESS = 'SUBMIT_SURVEY_SUCCESS';
